development:
  adapter: mysql2
  encoding: utf8
  database: gambling_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: gambling_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: gambling_production
  pool: 5
  username: root
  password:
  host: ''