defaults: &defaults
  time_zone: 'Taipei'
  pusher:
    app_id: '79453'
    key: '99ea86d44814ef7bd878'
    secret: 'edd75740bae5223e065f'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults